services:
  mysqldb:
    image: mysql:8.0
    env_file: ./.env
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysqldb
    environment:
      MYSQLDB_HOST: ${MYSQLDB_HOST}
      MYSQLDB_USER: ${MYSQLDB_USER}
      MYSQLDB_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQLDB_DOCKER_PORT: ${MYSQLDB_DOCKER_PORT}
    ports: 
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    volumes:
      - .:/myapp
      - /myapp/node_modules

volumes:
  db_data:
