services:
  mysqldb:
    image: mysql:8.0
    env_file: ./.env
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_PASSWORD=${MYSQLDB_PASSWORD}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - ./backend/src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysqldb
    environment:
      MYSQLDB_HOST: ${MYSQLDB_HOST}
      MYSQLDB_USER: ${MYSQLDB_USER}
      MYSQLDB_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQLDB_DATABASE: ${MYSQLDB_DATABASE}
      MYSQLDB_DOCKER_PORT: ${MYSQLDB_DOCKER_PORT}
    ports: 
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data:
