services:
  mysqldb:
    image: mysql:8.0
    env_file: ./.env
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_PASSWORD=${MYSQLDB_PASSWORD}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - ./backend/src/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./backend/src/database/data.sql:/docker-entrypoint-initdb.d/02-data.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      MYSQLDB_HOST: ${MYSQLDB_HOST}
      MYSQLDB_USER: ${MYSQLDB_USER}
      MYSQLDB_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQLDB_DATABASE: ${MYSQLDB_DATABASE}
      MYSQLDB_DOCKER_PORT: ${MYSQLDB_DOCKER_PORT}
    ports: 
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "${REACT_LOCAL_PORT}:${REACT_DOCKER_PORT}"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:${NODE_LOCAL_PORT}
    depends_on:
      - backend

volumes:
  db_data:
